### ISSUE TITLE
How to do a review for PRs created by Sourcery?

### ISSUE THREAD

**Issue by laike9m** [sourcery-ai/sourcery#128]
When reviewing a PR that Sourcery creates, what options do I have? I believe Sourcery won't reply to my comments, so I either accept all of the changes, or reject them. Is that correct?

**Comment by Hellebore** [comment]
Yes you've got that correct. 
In future we'd like to work on making it more interactive so that you can accept or reject changes. Unfortunately we're a small team and are currently focused on improving our PyCharm and VS Code plugins, so I'm not sure when we'll get round to that.

If you've got any suggestions for how you'd prefer it to work it would be great if you put them on this issue https://github.com/sourcery-ai/sourcery/issues/52 or dropped us an email.
