### ISSUE TITLE
Have the GitHub app do code reviews instead of separate PRs

### ISSUE THREAD

**Issue by br3ndonland** [sourcery-ai/sourcery#224]
Currently, Sourcery suggests refactorings by opening a separate PR, which will be merged into the original PR. All the refactorings are performed in a single commit, so if you want to reject one, you have to manually modify the code and push another commit. And there are some instances in which Sourcery will open multiple PRs (sourcery-ai/sourcery#223), which is probably unnecessary.

Instead, could the GitHub app perform a [code review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews) in the original PR? There would be some benefits to this:

- The Sourcery GitHub app wouldn't need to manage its own separate PRs
- Individual refactorings could be accepted or rejected on a line-by-line basis, by using the ["commit suggestion" feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request)

I think the app is nearly there already - it shows the diff after the proposed change, and makes comments explaining why. It would just be a matter of moving that functionality into the pull request review API.

What do you think?

Related:

- [GitHub docs: Pull requests - About pull request reviews](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews)
- [GitHub docs: Pull requests - Reviewing proposed changes in a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)
- [GitHub docs: Pull requests - Incorporating feedback in your pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request)
- [GitHub docs: REST API - Create a review comment for a pull request](https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request)

**Comment by ruancomelli** [comment]
This is indeed a great idea, and something we will look into in the next stages of our roadmap. Thanks for bringing this up!

How do you think this should work for "bulk accepts"? One advantage of having PRs instead of code reviews is that one can simply merge the Sourcery PR and have all changes merged, as opposed to having to manually accept each commit suggestion separately - with the downside that it gets harder to reject some of the changes.

**Comment by br3ndonland** [comment]
> How do you think this should work for "bulk accepts"? One advantage of having PRs instead of code reviews is that one can simply merge the Sourcery PR and have all changes merged, as opposed to having to manually accept each commit suggestion separately - with the downside that it gets harder to reject some of the changes.

Yeah, this is an important consideration. Thankfully GitHub has a "batch" feature, as they describe in the [docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request). You can add multiple suggestions to a "batch," then commit them all at the same time.

<img src="https://docs.github.com/assets/cb-20197/images/help/pull_requests/add-suggestion-to-batch.png" width="600px" />

**Comment by ruancomelli** [comment]
Hey @br3ndonland!

I know it's been a while since we last chatted, but I'd like to let you know that since then we've implemented a full PR review app - please refer to [our docs](https://docs.sourcery.ai/Code-Review/Code-Review-Introduction/) or [our main website](https://sourcery.ai/) for more details.

Note that this code-review app is mostly AI-powered, but you can keep the rules-based-only behavior by disabling the AI review functionality in your [Sourcery dashboard](https://sourcery.ai/dashboard).
