### ISSUE TITLE
Sourcery falsely identify project as closed source project

### ISSUE THREAD

**Issue by ilaner** [sourcery-ai/sourcery#374]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
I have an open source project, and one of the remotes is to a private repository. The `origin` is open source.
When running `sourcery review`, I get the following message
```
⠋ AuthenticatingYou are not logged in. Login is required for closed-source projects.
Please run:
$ sourcery login
to obtain your token through your browser.

Or input your token directly with:
$ sourcery login --token TOKEN

N.B. Sourcery is located here:
```

### Code snippet that reproduces issue

```

### Debug Information

IDE Version: 
Not relevant

Sourcery Version: 
1.6.0

Operating system and Version:
MacOS

**Comment by bm424** [comment]
Hi @ilaner, thank you for reporting this. To help us see what's happened, can you share a link to the repository you're working on?

**Comment by ilaner** [comment]
This is the repo link:
https://github.com/demisto/content

In my local git environment, I have set origin to `git@github.com:demisto/content.git`, and I have another remote to a private gitlab repo (which is unreachable from here).

**Comment by bm424** [comment]
Thanks @ilaner. I ran through the authentication logic for this repo and I can't see why it would have been identified as private. This leads me to conclude that it's likely that there was some internet connection issue or similar that prevented Sourcery from authenticating. I'm going to close this issue for now, because I don't think it's a general bug. However, I'd like to try to solve your specific problem - could you send your [Sourcery log file](https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log) to support@sourcery.ai? I'll be able to keep investigating from there.
