### ISSUE TITLE
No PR after starring sourcery on GitHub

### ISSUE THREAD

**Issue by pmeier** [sourcery-ai/sourcery#47]
This is either a bug report or an inappropriate complaint. Unfortunately, I don't have enough information to determine which is the case.

---

### Issue description or question

I wanted to give `sourcery` a try so I starred it here on GitHub. Directly afterwards @sourcery-ai-bot starred and [forked](https://github.com/sourcery-ai-bot/pystiche) the repository I wanted to be checked. I expected it to send a PR with all possible refactorings, but up until now (16h later) nothing happened. Could you check if everything is working as you expected it to do?

If that is the case and I'm just too impatient, could you tell me what the "normal" timeline is?

**Comment by Hellebore** [comment]
Hi there - looks like we've run into a bug on our end when creating your PR (it should show up pretty much straight away).

Will look into it.

**Comment by pmeier** [comment]
@Hellebore The bot opened the PR (see pmeier/pystiche#270). Thanks for the quick fix. If you need anything to help you debug feel free to reopen this.

**Comment by brendanator** [comment]
Thanks for raising @pmeier. Looks like the timeout of 1 minute wasn't long enough to refactor your repo. 

I also noticed that the comments describing each refactoring weren't there, which looks to be because the GitHub API has a limit on how many can be added at once. That is now fixed, but it took me a few tries to fix which explains why there are multiple updates to the PR
