### ISSUE TITLE
Refactor Master Option is Not Working

### ISSUE THREAD

**Issue by danyeaw** [sourcery-ai/sourcery#48]
I installed Sourcery as a GitHub Integration to an organization with open source repositories. I click on the refactor master button, and your website says: "Successful started refactoring job for master." I have told it to refactor multiple times over the last 24 hours, and there hasn't been a pull request made to the repo.

One of my co-developers did submit a PR, and sourcery-ai created a new PR with correction to it, so that part of the integration is working.

**Comment by brendanator** [comment]
Could you tell me which organization it is please and I'll investigate?

**Comment by danyeaw** [comment]
Thanks! The org and repo are both gaphor.

**Comment by brendanator** [comment]
This was down to Sourcery getting stuck in one area of the code and timing out. This has been fixed and the pull request is here - https://github.com/gaphor/gaphor/pull/341

Unfortunately due to the very large size of this PR there are not comments on every refactoring to explain what they are as GitHub API abuse rate limits were hit while creating the comments - https://developer.github.com/v3/#abuse-rate-limits. I will be investigating a work around for that separately

**Comment by danyeaw** [comment]
Thanks @brendanator for the fix!
