### ISSUE TITLE
Quality Metrics does not refresh/recalc after corrections made

### ISSUE THREAD

**Issue by bobgott** [sourcery-ai/sourcery#93]
### Issue description or question
I like the quality metrics report but after making some corrections and tapping 'refresh' (_from Sourcery tab - Refactoring Suggestions_) the report does not change.

Specifically, I have a report as follows:
Size - 219 (very poor) - Try splitting into smaller methods

I am assuming this is referring to the file where the warning occurs. I have split my file and my total lines are 130 but yet it says my code is 219.

Is it possible I am not reading the report correctly?

### Sourcery Version
0.8.1

Often available in Sourcery settings
All Defaults

### Code editor or IDE name and version

Pycharm v? 2020.2.3 (Professional Edition)

### OS name and version

Windows 10
![screenshot](https://user-images.githubusercontent.com/14927381/97580605-bf56b000-19b0-11eb-96d2-b137ff7f3a83.png)

**Comment by Hellebore** [comment]
Hi there! Thanks for raising.

The size actually refers to the method that it moves to when you click on the warning, which looks like the basic_gui method in this case. If you hover over the method name it should also pop up the metric information, though this happens a bit inconsistently in PyCharm if there are linting issues raised by other plugins/the IDE. It should update as soon as you make changes to the method rather than having to click refresh.

We're currently doing a pretty bad job of explaining what's going on - the next release (which should be coming early next week) will make the error message clearer (getting rid of the raw html) and add a clickable link in the hover so you can see how our metrics are being calculated (for instance the size refers to the number of code elements rather than lines, so you can't improve it by packing too much into each line).

I'll close this issue for now, but do reopen it (or email us at hello@sourcery.ai) if you have more questions/problems, or if I haven't gotten to the nub of the problem.

**Comment by bobgott** [comment]
```
for instance the size refers to the number of code elements rather than lines, 
so you can't improve it by packing too much into each line
```

That makes a lot of sense (_now that I understand the meaning of 'size'_).  Keep up the good work and thank you for the prompt response.
